name: linid_dev

services:
  db:
    image: postgres:18.4-alpine
    container_name: db
    networks:
      - linid-dev-network
    environment:
      POSTGRES_USER: ${DATABASE_ADMIN_USER}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./resources/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./resources/init_lemonldap_db.sql:/docker-entrypoint-initdb.d/init_lemonldap_db.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5

  auth:
    image: lemonldapng/lemonldap-ng:2.23
    container_name: lemon
    networks:
      - linid-dev-network
    environment:
      SSODOMAIN: ${LEMONLDAP_SSO_DOMAIN}
      PORTAL_HOSTNAME: ${LEMONLDAP_PORTAL_HOSTNAME}
    ports:
      - ${LEMONLDAP_PORTAL_PORT}:443
    volumes:
      - ./resources/llng/conf:/var/lib/lemonldap-ng/conf
      - ./resources/ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - ./resources/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
      - ./resources/oidc.key:/etc/keys/oidc.key:ro
      - ./resources/oidc.pub:/etc/keys/oidc.pub:ro
    depends_on:
      db:
        condition: service_healthy

  opa:
    image: openpolicyagent/opa:1.18.1
    container_name: opa
    networks:
      - linid-dev-network
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
    ports:
      - 8181:8181
    healthcheck:
      test: ["CMD", "/opa", "version"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  db-init:
    image: postgres:18.4-alpine
    container_name: init-db
    networks:
      - linid-dev-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_ADMIN_USER: ${DATABASE_ADMIN_USER}
      DATABASE_ADMIN_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PGPASSWORD: ${DATABASE_ADMIN_PASSWORD}
    volumes:
      - ./resources/init_data.sql:/init_data.sql:ro
      - ./resources/init_data.sh:/init_data.sh:ro
    entrypoint: ["/bin/sh", "/init_data.sh"]

networks:
  linid-dev-network:
    name: linid-dev-network
    driver: bridge
