name: linid_dev

services:
  db:
    image: postgres:18.4-alpine
    container_name: db
    networks:
      - linid-dev-network
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    volumes:
      - ../init-db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5

  init-db:
    image: postgres:18.4-alpine
    container_name: init-db
    networks:
      - linid-dev-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./env/db.env
    volumes:
      - ../init-db/scripts:/app/scripts:ro
      - ../init-db/init_data.sh:/app/init_data.sh:ro
    entrypoint: [ "/bin/sh", "/app/init_data.sh" ]

  lemon:
    image: lemonldapng/lemonldap-ng:2.23
    container_name: lemon
    networks:
      - linid-dev-network
    env_file:
      - ./env/lemon.env
    ports:
      - 8080:443
    volumes:
      - ./resources/llng/conf:/var/lib/lemonldap-ng/conf
      - ./resources/ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt:ro
      - ./resources/selfsigned.key:/etc/nginx/ssl/selfsigned.key:ro
      - ./resources/oidc.key:/etc/keys/oidc.key:ro
      - ./resources/oidc.pub:/etc/keys/oidc.pub:ro
    depends_on:
      db:
        condition: service_healthy

  opa:
    image: openpolicyagent/opa:1.18.1
    container_name: opa
    networks:
      - linid-dev-network
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
    ports:
      - 8181:8181
    healthcheck:
      test: ["CMD", "/opa", "version"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  superset:
    image: superset
    container_name: superset
    networks:
      - linid-dev-network
    env_file:
      - ./env/superset.env
    ports:
      - 8088:8443
    volumes:
      - ../superset/init_guest_role.py:/app/superset/init_guest_role.py:ro
      - ./resources/superset.crt:/app/certs/superset.crt:ro
      - ./resources/superset.key:/app/certs/superset.key:ro
    depends_on:
      - db

  init-superset:
    image: curlimages/curl:latest
    container_name: init-superset
    networks:
      - linid-dev-network
    env_file:
      - ./env/superset.env
    depends_on:
      - superset
    user: root
    entrypoint: [ "sh", "-c", "apk add --no-cache jq zip && /app/superset/init_data_superset.sh" ]
    volumes:
      - ../superset/dashboard_export.zip:/app/superset/dashboard_export.zip:ro
      - ../superset/init_data_superset.sh:/app/superset/init_data_superset.sh:ro
    working_dir: /app/superset

networks:
  linid-dev-network:
    name: linid-dev-network
    driver: bridge
