#!/bin/bash

echo "=============================================="
echo "  Linid Identity Manager - Local Demo Launcher"
echo "=============================================="
echo ""
echo "This script builds all required Docker images and starts the demo environment locally."
echo "Make sure Docker and Docker Compose are installed on your machine."
echo ""

echo "📦 Building Docker image: fake external api..."
docker build -t mock-api docker/mock-api/

clear
echo "📦 Building Docker image: linid-im-api..."
docker build -f linid-im-api/docker/Dockerfile -t linid-im-api linid-im-api/

clear
echo "📦 Building Docker image: linid-im-front..."
docker build -f linid-im-front/docker/Dockerfile -t linid-im-front linid-im-front/

clear
echo "📦 Building Docker image: catalog-ui..."
docker build -f linid-im-front-community-plugins/docker/catalog-ui.Dockerfile -t catalog-ui linid-im-front-community-plugins/

clear
echo "📦 Building Docker image: module-users..."
docker build -f linid-im-front-community-plugins/docker/module-users.Dockerfile -t module-users linid-im-front-community-plugins/

clear
echo ""
echo "🧹 Cleaning unused Docker containers and volumes..."
docker container prune -f && docker volume prune -f

clear
echo ""
echo "🚀 Starting Linid Identity Manager in demo mode..."
docker compose -f docker/demo/docker-compose.yml --env-file docker/demo/.env up
