authorization:
  type: allow-all

tasks:
  - type: json-parsing
    name: parseJsonResponse
    source: response
    destination: response
  - type: context-mapping
    name: format-response
    mapping:
      response: response
    templates:
      response.response: '{ "content": {{context.response}} }'

routes:
  - type: dynamic-list
    route: /options/statuses
    url: http://mock-api:3000/api/statuses
    method: GET
    tasks:
      - name: format-response
        phases:
          - beforeDynamicListMapping
      - name: parseJsonResponse
        phases:
          - beforeDynamicListMapping
    page: 0
    size: 200
    total: "{{ context.response.content.size() }}"
    itemsCount: "{{ context.response.content.size() }}"
    elementMapping:
      label: "{{ context.response.content[index].label }}"
      value: "{{ context.response.content[index].id }}"

providers:
  - name: http-provider
    type: http
    baseUrl: http://mock-api:3000
    headers:
      Content-Type: application/json

entities:
  - name: user
    route: users
    provider: http-provider
    tasks:
      - name: parseJsonResponse
        phases:
          - beforeResponseMappingFindAll
          - beforeResponseMappingFindById
          - beforeResponseMappingCreate
          - beforeResponseMappingUpdate
          - beforeResponseMappingPatch
    access:
      findAll:
        uri: "/api/users?page={{ context.pageable.pageNumber }}&size={{ context.pageable.pageSize }}{% if context.filters.email %}&email={{ context.filters.email[0] }}{% endif %}{% if context.filters.firstName %}&firstName={{ context.filters.firstName[0] }}{% endif %}{% if context.filters.lastName %}&lastName={{ context.filters.lastName[0] }}{% endif %}"
        method: GET
        page: "{{ context.response.pageable.pageNumber }}"
        size: "{{ context.response.pageable.pageSize }}"
        total: "{{ context.response.totalElements }}"
        itemsCount: "{{ context.response.content | length }}"
        entityMapping:
          id: "{{ context.response.content[index].id }}"
          email: "{{ context.response.content[index].email }}"
          firstName: "{{ context.response.content[index].firstName }}"
          lastName: "{{ context.response.content[index].lastName }}"
          displayName: "{{ context.response.content[index].displayName }}"
          enabled: "{{ context.response.content[index].enabled }}"
          role: "{{ context.response.content[index].role }}"
          dateOfBirth: "{{ context.response.content[index].dateOfBirth | replace('-', '/') }}"
          status: "{{ context.response.content[index].status }}"
      findById:
        uri: "/api/users/{{ context.id }}"
        method: GET
        entityMapping:
          id: "{{ context.response.id }}"
          email: "{{ context.response.email }}"
          firstName: "{{ context.response.firstName }}"
          lastName: "{{ context.response.lastName }}"
          displayName: "{{ context.response.displayName }}"
          enabled: "{{ context.response.enabled }}"
          role: "{{ context.response.role }}"
          dateOfBirth: "{{ context.response.dateOfBirth | replace('-', '/') }}"
          status: "{{ context.response.status }}"
      create:
        uri: /api/users
        method: POST
        body: "{{ entity | tojson }}"
        entityMapping:
          id: "{{ context.response.id }}"
          email: "{{ context.response.email }}"
          firstName: "{{ context.response.firstName }}"
          lastName: "{{ context.response.lastName }}"
          displayName: "{{ context.response.displayName }}"
          enabled: "{{ context.response.enabled }}"
          role: "{{ context.response.role }}"
          dateOfBirth: "{{ context.response.dateOfBirth | replace('/', '-') }}"
          status: "{{ context.response.status }}"
      update:
        uri: "/api/users/{{ context.id }}"
        method: PUT
        body: "{{ entity | tojson }}"
        entityMapping:
          id: "{{ context.response.id }}"
          email: "{{ context.response.email }}"
          firstName: "{{ context.response.firstName }}"
          lastName: "{{ context.response.lastName }}"
          displayName: "{{ context.response.displayName }}"
          enabled: "{{ context.response.enabled }}"
          role: "{{ context.response.role }}"
          dateOfBirth: "{{ context.response.dateOfBirth | replace('/', '-') }}"
          status: "{{ context.response.status }}"
      patch:
        uri: "/api/users/{{ context.id }}"
        method: PATCH
        body: "{{ entity | tojson }}"
        entityMapping:
          id: "{{ context.response.id }}"
          email: "{{ context.response.email }}"
          firstName: "{{ context.response.firstName }}"
          lastName: "{{ context.response.lastName }}"
          displayName: "{{ context.response.displayName }}"
          enabled: "{{ context.response.enabled }}"
          role: "{{ context.response.role }}"
          dateOfBirth: "{{ context.response.dateOfBirth | replace('/', '-') }}"
          status: "{{ context.response.status }}"
      delete:
        uri: "/api/users/{{ context.id }}"
        method: DELETE
        result: "true"
    attributes:
      - name: id
        type: String
        input: Text
      - name: email
        type: String
        required: true
        input: Text
        inputSettings:
          pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        validations:
          - type: required
            phases: [ beforeCreate, beforeUpdate ]
          - type: regex
            pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.com$"
            phases: [ beforeCreate, beforeUpdate ]
      - name: firstName
        type: String
        required: true
        input: Text
        inputSettings:
          minLength: 3
          maxLength: 20
        validations:
          - type: required
            phases: [ beforeCreate, beforeUpdate ]
      - name: lastName
        type: String
        required: true
        input: Text
        inputSettings:
          minLength: 3
          maxLength: 20
        validations:
          - type: required
            phases: [ beforeCreate, beforeUpdate ]
      - name: displayName
        type: String
        input: Text
      - name: enabled
        type: Boolean
        input: Boolean
      - name: role
        type: String
        input: Text
      - name: dateOfBirth
        type: String
        input: Date
      - name: status
        type: String
        input: DynamicList
        inputSettings:
          route: /options/statuses
        validations:
          - type: dynamic-list
            url: http://mock-api:3000/api/statuses
            method: GET
            tasks:
              - name: format-response
                phases:
                  - beforeDynamicListMapping
              - name: parseJsonResponse
                phases:
                  - beforeDynamicListMapping
            page: 0
            size: 200
            total: "{{ context.response.content.size() }}"
            itemsCount: "{{ context.response.content.size() }}"
            elementMapping:
              label: "{{ context.response.content[index].label }}"
              value: "{{ context.response.content[index].id }}"
