spring:
  application:
    name: LinId-Identity-Manager

  config:
    import: optional:file:${EXTERNAL_CONFIGURATION}

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_ADMIN_USER}
    password: ${DATABASE_ADMIN_PASSWORD}
    client:
      schema: ${CLIENT_DATABASE_SCHEMA:public}
      location: ${CLIENT_DATABASE_MIGRATION_PATH:}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          jwk-set-uri: ${AUTH_JWK_SET_URI}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}
  show-actuator: ${SWAGGER_ENABLED}

server:
  port: 8443
  ssl:
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_PASSWORD}
    key-password: ${SSL_KEY_PASSWORD}
    truststore:
      path: ${SSL_TRUSTSTORE_PATH}
      password: ${SSL_TRUSTSTORE_PASSWORD}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

copyright:
  mode: ${COPYRIGHT_MODE:default}
  default: "© 2020-2026 Linagora. All rights reserved."
  custom: "${COPYRIGHT_CUSTOM:© 2020-2025 Linagora. All rights reserved.}"

i18n:
  external:
    path: ${I18N_EXTERNAL_PATH:}
  merge:
    order: ${I18N_MERGE_ORDER:plugin,external,internal}

plugin:
  loader:
    path: ${PLUGIN_LOADER_PATH:}

opa:
  script:
    location: ${OPA_SCRIPT_LOCATION:classpath:templates/opa/opa-policy.rego.j2}
    policy-path: ${OPA_POLICY_PATH:/v1/policies/{id}}
  deployment:
    server-url: ${OPA_SERVER_URL:http://opa:8181}
    interval: ${OPA_DEPLOYMENT_INTERVAL:5m}
