name: linid_integration

services:
  db:
    image: postgres:18.4-alpine
    container_name: db
    networks:
      - linid-e2e-network
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
    volumes:
      - ../init-db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 5

  init-db:
    image: postgres:18.4-alpine
    container_name: init-db
    networks:
      - linid-e2e-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./env/db.env
    volumes:
      - ../init-db/scripts:/app/scripts:ro
      - ../init-db/init_data.sh:/app/init_data.sh:ro
    entrypoint: [ "/bin/sh", "/app/init_data.sh" ]

  auth:
    image: lemonldapng/lemonldap-ng:2.23
    container_name: lemon
    networks:
      - linid-e2e-network
    env_file:
      - ./env/lemon.env
      - ./env/${ENV}.env
    ports:
      - 8080:80
    volumes:
      - ./resources/${CONFIG_DIR}/llng/conf:/var/lib/lemonldap-ng/conf
      - ./resources/oidc.key:/etc/keys/oidc.key:ro
      - ./resources/oidc.pub:/etc/keys/oidc.pub:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-check-certificate --spider -q --header=\"Host: $$SSODOMAIN\" \"http://127.0.0.1/checkstate?secret=$$LEMONLDAP_CHECKSTATE_SECRET\""
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy

  opa:
    image: openpolicyagent/opa:1.18.1
    container_name: opa
    networks:
      - linid-e2e-network
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
    ports:
      - 8181:8181
    healthcheck:
      test: ["CMD", "/opa", "version"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  api:
    image: linid-identity-manager-api
    container_name: api
    networks:
      - linid-e2e-network
    extra_hosts:
      - "linid.localtest.me:host-gateway"
    ports:
      - 8443:8443
    env_file:
      - ./env/api.env
      - ./env/${ENV}.env
    volumes:
      - ./resources/truststore.jks:/etc/ssl/truststore.jks:ro
      - ./resources/superset.yaml:/app/superset.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/8443' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      auth:
        condition: service_healthy
      db:
        condition: service_healthy
      opa:
        condition: service_healthy

  ui:
    image: linid-identity-manager-ui
    container_name: ui
    networks:
      - linid-e2e-network
    ports:
      - 9000:443
    environment:
      APP_ENV: ${ENVIRONMENT}
    volumes:
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources/selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./resources/selfsigned.key:/etc/nginx/certs/selfsigned.key:ro
      - ./resources/remotes.json:/usr/share/nginx/html/remotes.json:ro
      - ./resources/${CONFIG_DIR}/oidc/conf/oidc-config.json:/usr/share/nginx/html/oidc-config.json:ro
    depends_on:
      catalog-ui:
        condition: service_started
      api:
        condition: service_healthy
      auth:
        condition: service_healthy

  catalog-ui:
    image: catalog-ui
    container_name: catalog-ui
    networks:
      - linid-e2e-network
    volumes:
      - ./resources/nginx-modules.conf:/etc/nginx/nginx.conf:ro

  e2e-test-runner:
    image: vincentmoittie/e2e-test-runner:v1.13.0
    container_name: e2e-test-runner
    networks:
      - linid-e2e-network
    env_file:
      - ./env/${ENV}.env
    volumes:
      - ../../tests/features:/app/features
    depends_on:
      api:
        condition: service_healthy
      ui:
        condition: service_started
      init-db:
        condition: service_completed_successfully
    profiles:
      - test

  superset:
    image: superset
    container_name: superset
    networks:
      - linid-e2e-network
    env_file:
      - ./env/superset.env
    ports:
      - 8088:8443
    volumes:
      - ../superset/init_guest_role.py:/app/superset/init_guest_role.py:ro
      - ./resources/superset.crt:/app/certs/superset.crt:ro
      - ./resources/superset.key:/app/certs/superset.key:ro
    depends_on:
      db:
        condition: service_healthy

  init-superset:
    image: curlimages/curl:latest
    container_name: init-superset
    networks:
      - linid-e2e-network
    env_file:
      - ./env/superset.env
    depends_on:
      superset:
        condition: service_healthy
    user: root
    entrypoint: [ "sh", "-c", "apk add --no-cache jq zip && /app/superset/init_data_superset.sh" ]
    volumes:
      - ../superset/dashboard_export.zip:/app/superset/dashboard_export.zip:ro
      - ../superset/init_data_superset.sh:/app/superset/init_data_superset.sh:ro
    working_dir: /app/superset

networks:
  linid-e2e-network:
    name: linid-e2e-network
    driver: bridge
