CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE ROLE linid_user WITH LOGIN PASSWORD 'password';
GRANT USAGE ON SCHEMA public TO linid_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO linid_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO linid_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO linid_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE ON SEQUENCES TO linid_user;
