name: Pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: 22.19
  PNPM_VERSION: 10.32.1

jobs:
  delete-comments:
    name: Delete bot comment(s)
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@d075704468e1cf74e60944d9f335351213c34d85
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}

  branch-naming-rules:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@5f1cc199284b75145ec2d13434422e6987cf6af8
        with:
          regex: '^(feature|bugfix|improvement|release|hotfix)\/[a-z0-9_.-]+$'
          allowed_prefixes: "feature,bugfix,improvement,release,hotfix"
          ignore: main
          min_length: 5
          max_length: 50

  commit-checks:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install commitlint
        run: npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: Run commitlint
        run: |
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.cjs
          npx commitlint --from=origin/main --to=HEAD --verbose

  ui-build:
    name: UI - Build application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          working-directory: ui

      - name: Build application
        run: pnpm build

  ui-check-style:
    name: UI - Code style
    runs-on: ubuntu-latest
    needs: [ui-build]
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          working-directory: ui

      - name: Check style
        run: pnpm validate

  ui-unit-tests:
    name: UI - Unit tests
    runs-on: ubuntu-latest
    needs: [ui-build]
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          working-directory: ui

      - name: Run unit tests
        run: |
          set -o pipefail
          echo '```bash' > coverage.txt
          pnpm test:ci | sed 's/\x1b\[[0-9;]*m//g' >> coverage.txt
          echo '```' >> coverage.txt

      - name: Comment PR
        if: success()
        uses: JoseThen/comment-pr@v1.2.0
        with:
          file_path: ui/coverage.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ui-check-dependencies:
    name: UI - Check dependencies
    runs-on: ubuntu-latest
    needs: [ui-build]
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          working-directory: ui

      - name: Check outdated dependencies
        run: |
          pnpm add -D npm-check-updates
          echo '```bash' > dependencies.txt
          npx ncu >> dependencies.txt
          echo '```' >> dependencies.txt

      - name: Comment PR
        uses: JoseThen/comment-pr@v1.2.0
        with:
          file_path: ui/dependencies.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  api-check-style:
    name: API - Code style
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21 for x64 (with Maven cache)
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
          cache: maven

      - name: Execute checkstyle
        run: mvn -ntp checkstyle:check

  api-javadoc:
    name: API - Javadoc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21 for x64 (with Maven cache)
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
          cache: maven

      - name: Generate Javadoc
        run: mvn -ntp clean javadoc:javadoc

  api-tests:
    name: API - Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21 for x64 (with Maven cache)
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
          cache: maven

      - name: Execute unit tests
        run: mvn -ntp test

      - name: Execute mutation tests
        run: mvn -ntp org.pitest:pitest-maven:mutationCoverage

      - name: Extract summary from pitest
        run: echo "<html><head></head><body><h1>Pit Test Coverage Report</h1><h3>Project Summary</h3>" > pitest.html && perl -0777 -ne 'print "$1\n" if /(<table>.*?<\/table>)/s' target/pit-reports/index.html >> pitest.html && echo "</body></html>" >> pitest.html

      - name: Post comment
        uses: luukkemp/pr-comment@a36dd289fd0052e576955cd09d126449404d633b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: api/pitest.html

  api-check-dependencies:
    name: API - Check dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21 for x64 (with Maven cache)
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
          cache: maven

      - name: Execute check dependencies
        run: mvn -ntp versions:display-dependency-updates -DprocessDependencyManagement=false > dependency-updates.txt

      - name: Post comment
        uses: luukkemp/pr-comment@a36dd289fd0052e576955cd09d126449404d633b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: api/dependency-updates.txt

  e2e-check-style:
    name: E2E - Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: tests/e2e
        run: npm ci

      - name: Check style
        working-directory: tests/e2e
        run: E2E_SPEC_PATTERN=../features npm run lint

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: [api-tests]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run e2e tests
        run: |
          task setup
          task start:test:ci

      - name: Stop docker services
        if: always()
        working-directory: docker/e2e
        run: docker compose down
